url: https://vikasdhiman.info
baseurl: /ECE275-Sequential-Logic
remote_theme:  samarsault/plainwhite-jekyll
title: Sequential Logic Systems (ECE275) at the University of Maine
author: Vikas Dhiman
description: Sequential Logic Systems (ECE275) at the University of Maine
show_excerpts: true

# Build settings
markdown: kramdown
permalink: pretty
paginate: 10


header_pages:
  - schedule.md
  - syllabus.md
  - labnotes.md
  - category/lecture


plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme

plainwhite:
  name: Sequential Logic Systems (ECE275)
  tagline: |
     Boolean algebra, Flip-flops, K-Maps, Verilog

  sitemap: true

  search: true

  html_lang: "en"

  navigation:
    - title: Syllabus
      url: "/syllabus"
    - title: Schedule
      url: "/schedule"
    - title: Lab Notes
      url: "/labnotes"
    - title: Course feedback
      url: https://docs.google.com/forms/d/e/1FAIpQLScX9rWaFGDKy-7FuAazdjeMPRQGnBM6kn17jhl5JfRqmr83cw/viewform?usp=sf_link
    - title: Similar courses
      url: "/similar-courses"

  portfolio_image: images/Transistor_Bistable_interactive_animated-en.svg
    
  condensed_mobile:
    - home
    - post
    - page
